-- 코드를 입력하세요
SELECT outs.ANIMAL_ID, outs.ANIMAL_TYPE, outs.NAME
FROM ANIMAL_OUTS outs
LEFT JOIN ANIMAL_INS ins ON outs.ANIMAL_ID = ins.ANIMAL_ID
WHERE outs.SEX_UPON_OUTCOME != ins.SEX_UPON_INTAKE
ORDER BY outs.ANIMAL_ID