-- 코드를 입력하세요
SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT fp
    JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID asc