-- 코드를 입력하세요
SELECT ap.APNT_NO, p.PT_NAME, p.PT_NO, ap.MCDP_CD, d.DR_NAME, ap.APNT_YMD
FROM APPOINTMENT ap
    JOIN DOCTOR d ON ap.MDDR_ID = d.DR_ID
        JOIN PATIENT p ON ap.PT_NO = p.PT_NO 
WHERE ap.APNT_YMD LIKE '2022-04-13%' AND ap.APNT_CNCL_YN = 'N' AND ap.MCDP_CD = 'CS'
ORDER BY ap.APNT_YMD ASC